//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch
    {
        public int ID { get; set; }
        public string BatchID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FromEmail { get; set; }
        public string EmailSubject { get; set; }
        public string EmailContentType { get; set; }
        public string EmailBody { get; set; }
        public string Link { get; set; }
        public string To { get; set; }
        public string cc { get; set; }
        public string EmailIdentifier { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string MSP { get; set; }
        public string DownloadPath { get; set; }
        public string message_id { get; set; }
        public Nullable<bool> PartialResponseSent { get; set; }
        public Nullable<bool> FinalResponseSent { get; set; }
    }
}
