//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorcodemasterdistinct_bkp24042020
    {
        public int ID { get; set; }
        public string errorcode { get; set; }
        public string Remarks { get; set; }
        public string Type { get; set; }
        public string ErrorBucket { get; set; }
    }
}
