//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorcodemaster_bkp24042020
    {
        public int ID { get; set; }
        public string ErrorCode { get; set; }
        public string Remarks { get; set; }
        public string Type { get; set; }
        public string ErrorBucket { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Machine_Make { get; set; }
        public string Module_code { get; set; }
        public string Module_Discreption { get; set; }
        public string TD_status { get; set; }
        public string TD_status_Discreption { get; set; }
        public string M_status_error { get; set; }
        public string M_status_error_Discreption { get; set; }
        public Nullable<bool> NextTrans_Flag { get; set; }
    }
}
