//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class RMSAutomation_UATEntities : DbContext
    {
        public RMSAutomation_UATEntities()
            : base("name=RMSAutomation_UATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apilog> apilogs { get; set; }
        public virtual DbSet<atmmaster> atmmasters { get; set; }
        public virtual DbSet<batch> batches { get; set; }
        public virtual DbSet<batchresponse> batchresponses { get; set; }
        public virtual DbSet<CassetteMaster> CassetteMasters { get; set; }
        public virtual DbSet<EmailData> EmailDatas { get; set; }
        public virtual DbSet<employee_hierarchy> employee_hierarchy { get; set; }
        public virtual DbSet<employee_role> employee_role { get; set; }
        public virtual DbSet<errorcodemaster> errorcodemasters { get; set; }
        public virtual DbSet<errorcodemasterdistinct> errorcodemasterdistincts { get; set; }
        public virtual DbSet<errorrolemapping> errorrolemappings { get; set; }
        public virtual DbSet<master> masters { get; set; }
        public virtual DbSet<mspconfiguration> mspconfigurations { get; set; }
        public virtual DbSet<oldrmsticket> oldrmstickets { get; set; }
        public virtual DbSet<physical_shortage_temp> physical_shortage_temp { get; set; }
        public virtual DbSet<recovery> recoveries { get; set; }
        public virtual DbSet<recoverycollection> recoverycollections { get; set; }
        public virtual DbSet<runruleenginelog> runruleenginelogs { get; set; }
        public virtual DbSet<StatusChangeManual> StatusChangeManuals { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<Ticket_CounterData> Ticket_CounterData { get; set; }
        public virtual DbSet<ticket_DUP> ticket_DUP { get; set; }
        public virtual DbSet<ticketattachment> ticketattachments { get; set; }
        public virtual DbSet<ticketlog> ticketlogs { get; set; }
        public virtual DbSet<userloginhistory> userloginhistories { get; set; }
        public virtual DbSet<utilization_data> utilization_data { get; set; }
        public virtual DbSet<utilization_data_logs> utilization_data_logs { get; set; }
        public virtual DbSet<atmmaster_bkp_06042020> atmmaster_bkp_06042020 { get; set; }
        public virtual DbSet<atmmasterbkp> atmmasterbkps { get; set; }
        public virtual DbSet<batch_bkp_06042020> batch_bkp_06042020 { get; set; }
        public virtual DbSet<errorcodemaster_bkp24042020> errorcodemaster_bkp24042020 { get; set; }
        public virtual DbSet<errorcodemasterdistinct_bkp24042020> errorcodemasterdistinct_bkp24042020 { get; set; }
        public virtual DbSet<ticket_bkp_06042020> ticket_bkp_06042020 { get; set; }
        public virtual DbSet<ticket_bkp_08032020> ticket_bkp_08032020 { get; set; }
        public virtual DbSet<ticket_dup_bkp_06042020> ticket_dup_bkp_06042020 { get; set; }
        public virtual DbSet<ticketattachments_bkp_06042020> ticketattachments_bkp_06042020 { get; set; }
        public virtual DbSet<ticketlog_bkp_06042020> ticketlog_bkp_06042020 { get; set; }
        public virtual DbSet<utilization_data_bkp_06042020> utilization_data_bkp_06042020 { get; set; }
    }
}
