//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mspconfiguration
    {
        public int ID { get; set; }
        public string DomainName { get; set; }
        public string MSPName { get; set; }
        public string ATMID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Password { get; set; }
        public string ImageLogo { get; set; }
        public Nullable<bool> NoExcessCertificateReq { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
