//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class physical_shortage_temp
    {
        public int ID { get; set; }
        public Nullable<long> CBRID { get; set; }
        public string ATMID { get; set; }
        public Nullable<System.DateTime> EODDATETIME { get; set; }
        public Nullable<System.DateTime> EODDATE { get; set; }
        public Nullable<System.DateTime> TRANTIME { get; set; }
        public Nullable<double> Overage_Total { get; set; }
        public Nullable<double> Shortage_Total { get; set; }
        public Nullable<double> Overage_2000 { get; set; }
        public Nullable<double> Overage_500 { get; set; }
        public Nullable<double> Overage_200 { get; set; }
        public Nullable<double> Overage_100 { get; set; }
        public Nullable<double> Overage_50 { get; set; }
        public Nullable<double> Shortage_2000 { get; set; }
        public Nullable<double> Shortage_500 { get; set; }
        public Nullable<double> Shortage_200 { get; set; }
        public Nullable<double> Shortage_10 { get; set; }
        public Nullable<double> Shortage_50 { get; set; }
    }
}
