//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recovery
    {
        public int RecoveryId { get; set; }
        public string RecoveryNo { get; set; }
        public string BatchId { get; set; }
        public string TicketId { get; set; }
        public string RefTicketId { get; set; }
        public string RecoveryFromEmpId { get; set; }
        public string EmployeeName { get; set; }
        public string Status { get; set; }
        public string Status2 { get; set; }
        public Nullable<double> RecoveryAmount { get; set; }
        public Nullable<double> ReceivedAmount { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string RecoveryAssignedTo { get; set; }
    }
}
