//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class runruleenginelog
    {
        public int ID { get; set; }
        public string BatchID { get; set; }
        public string TicketID { get; set; }
        public Nullable<bool> RanRuleEngineWeb { get; set; }
        public Nullable<System.DateTime> RanRuleEngineWebDate { get; set; }
        public string RuleEngineRemarks { get; set; }
        public string RuleEngineInitiator { get; set; }
    }
}
