//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusChangeManual
    {
        public int Id { get; set; }
        public Nullable<int> SrNo { get; set; }
        public string Justification { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public string OldCMSStatus { get; set; }
        public string NewCMSStatus { get; set; }
        public string ModifiedBy { get; set; }
    }
}
