//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketattachments_bkp_06042020
    {
        public int Id { get; set; }
        public string TicketId { get; set; }
        public Nullable<bool> VisibleToMSP { get; set; }
        public Nullable<bool> VisibleToHO { get; set; }
        public Nullable<bool> VisibleToLocation { get; set; }
        public string TypeOfAttachment { get; set; }
        public string FilePath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> EmailSentTime { get; set; }
        public string EmailType { get; set; }
    }
}
