//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticketlog_bkp_06042020
    {
        public int ID { get; set; }
        public string MSP { get; set; }
        public string BatchID { get; set; }
        public string TicketID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> DisputeRejected { get; set; }
        public string Justification { get; set; }
        public string InternalAction { get; set; }
        public string UploadedFileName { get; set; }
        public string UploadedFile { get; set; }
        public string CustCommentsType { get; set; }
        public string CustCommentsBy { get; set; }
        public string CustComments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AssignedTo { get; set; }
        public string Source { get; set; }
    }
}
