//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_CounterData
    {
        public int Id { get; set; }
        public string TicketID { get; set; }
        public string ATMID { get; set; }
        public Nullable<System.DateTime> EODDate { get; set; }
        public string QueryType { get; set; }
        public string CountertType { get; set; }
        public string SubType { get; set; }
        public Nullable<long> Deno50 { get; set; }
        public Nullable<long> Deno100 { get; set; }
        public Nullable<long> Deno200 { get; set; }
        public Nullable<long> Deno500 { get; set; }
        public Nullable<long> Deno1000 { get; set; }
        public Nullable<long> Deno2000 { get; set; }
        public Nullable<long> Total { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
